// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "auth": {
    "login": {
      "title": "Login to your account",
      "description": "Enter your email below to login to your account",

      "email": {
        "label": "Email",
        "placeholder": "m@example.com"
      },

      "password": {
        "label": "Password",
        "placeholder": "Enter your password"
      },

      "buttons": {
        "login": "Login",
        "loginWithGoogle": "Login with Google",
         "loading": "Loading..."
      },

      "footer": {
        "noAccount": "Don't have an account?",
        "signUp": "Sign up"
      },

      "errors": {
        "inactive": "Your account isn’t active yet. Please",
        "activate": "click here to activate it",
        "unauthorized": "Incorrect email or password.",
         "unknown": "Something went wrong. Please try again.",

        "validation": {
          "email": {
            "required": "Please enter your email",
            "invalid": "Please enter a valid email"
          },

          "password": {
            "min": "Password must be at least 8 characters",
            "uppercase": "Must contain at least one uppercase letter",
            "lowercase": "Must contain at least one lowercase letter",
            "number": "Must contain at least one number",
            "special": "Must contain at least one special character",
            "mismatch": "Passwords do not match"
          },

          "firstName": {
            "min": "First name must be at least 2 characters",
            "invalid": "First name can only contain letters"
          },

          "lastName": {
            "min": "Last name must be at least 2 characters",
            "invalid": "Last name can only contain letters"
          },

          "confirmPassword": {
            "required": "Please confirm your password"
          },

          "code": {
            "min": "Code must be 6 digits"
          }
        }
      }
    }
  }
};
export default messages;