// import type { Metadata } from "next";
// import "./globals.css";
// import { Toaster } from "sonner";
// import NextAuthWrapper from "@/lib/nextauth-wrapper";
// import { TooltipProvider } from "@/components/ui/tooltip";
// import { geist, outfit } from "@/fonts";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={`${geist.variable} ${outfit.variable} text-base`}>
//       <body className={`antialiased bg-neutral-50`}>
//         <NextAuthWrapper >
//           <TooltipProvider> {children}</TooltipProvider>
//         </NextAuthWrapper>
//         <Toaster className="z-[9999]"/>
//       </body>
//     </html>
//   );
// }

import {ReactNode} from 'react';
import './globals.css';

type Props = {
  children: ReactNode;
};

// Since we have a `not-found.tsx` page on the root, a layout file
// is required, even if it's just passing children through.
export default function RootLayout({children}: Props) {
  return children;
}

