import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/fonts";
import { Toaster } from "@/components/ui/sonner";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import NextAuthWrapper from "@/lib/nextauth-wrapper";
import { TooltipProvider } from "@/components/ui/tooltip";
const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${inter.className} antialiased bg-neutral-50`}>
        <NextAuthWrapper>
          <TooltipProvider> {children}</TooltipProvider>
        </NextAuthWrapper>
        <Toaster />
      </body>
    </html>
  );
}
